--DROP VIEW IF EXISTS vw_tdw;
--DROP VIEW IF EXISTS ww_invest_certificates;
--DROP VIEW IF EXISTS vw_invest_accounts;
DROP VIEW IF EXISTS vw_cd_sum;

--
DROP TABLE IF EXISTS Withdraws;
DROP TABLE IF EXISTS Deposits;
-- ROLLBACK; commit;

DROP TABLE IF EXISTS CheckingAccounts;
DROP TABLE IF EXISTS Certificates_of_deposit;
--
DROP TABLE IF EXISTS Transfers;
DROP TABLE IF EXISTS InvestmentAccounts;
DROP TABLE IF EXISTS Manages;
--
DROP TABLE IF EXISTS Accounts;
--
DROP TABLE IF EXISTS Employees CASCADE;
DROP TABLE IF EXISTS Customers CASCADE ;
DROP TABLE IF EXISTS MinSP CASCADE;
DROP TABLE IF EXISTS Profil CASCADE;
DROP TABLE IF EXISTS Profiler CASCADE;
DROP TABLE IF EXISTS Proevesvar CASCADE;
DROP TABLE IF EXISTS Aftaler CASCADE;
DROP TABLE IF EXISTS Meddelelser CASCADE;
DROP TABLE IF EXISTS Journalnotater CASCADE;
DROP TABLE IF EXISTS Diagnoser_allergier CASCADE;
DROP TABLE IF EXISTS Indsigelser CASCADE;
