DROP TABLE IF EXISTS Profiler CASCADE;
DROP TABLE IF EXISTS Proevesvar CASCADE;
DROP TABLE IF EXISTS Aftaler CASCADE;
DROP TABLE IF EXISTS Meddelelser CASCADE;
DROP TABLE IF EXISTS Journalnotater CASCADE;
DROP TABLE IF EXISTS Diagnoser_allergier CASCADE;
DROP TABLE IF EXISTS Indsigelser CASCADE;
